version: "3.8"
services:
  gpu-jupyter:
    build:
      context: .build
      args:
        NB_USER: "emp"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    ports:
      - 8848:8888
      - 5005:5000
    volumes:
      - ./data:/home/$NB_USER/work
      - hf_cache:/home/$NB_USER/.cache/huggingface/hub
    environment:
      # enable sudo permissions
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
      NB_UID: ${JUPYTER_UID:-1000}
      NB_GID: ${JUPYTER_GID:-1000}
      MLFLOW_S3_ENDPOINT_URL: "http://172.16.20.150:9000"
      MLFLOW_TRACKING_URI: "http://172.16.20.150:5000"
      AWS_ACCESS_KEY_ID: "admin"
      AWS_SECRET_ACCESS_KEY: "sample_key"
    user:
      "root"
    restart: always
    shm_size: '2gb'
    image: ncicto/gpu-jupyter_py39
    container_name: gpu-jupyter_py39
volumes:
  hf_cache:
