version: "3.8"
services:
  gpu-jupyter:
    build: .build
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    ports:
      - 8848:8888
    volumes:
      - ./data:/home/jovyan/work
      - hf_cache:/home/jovyan/.cache/huggingface/hub
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
      NB_UID: ${JUPYTER_UID:-1000}
      NB_GID: ${JUPYTER_GID:-1000}
      MLFLOW_S3_ENDPOINT_URL: "http://172.16.20.150:9000"
      MLFLOW_TRACKING_URI: "http://172.16.20.150:5000"
      AWS_ACCESS_KEY_ID: "admin"
      AWS_SECRET_ACCESS_KEY: "sample_key"
    # enable sudo permissions
    user:
      "root"
    restart: always
    shm_size: '2gb'
volumes:
  hf_cache:
